name: Dependabot Auto-label and Rename

on:
  pull_request_target:
    types: [opened]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Label PR
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add chore(deps) prefix
        run: |
          PR_TITLE=$(gh pr view ${{ github.event.pull_request.number }} --json title -q .title)
          if [[ ! "$PR_TITLE" =~ ^chore\(deps\): ]]; then
            NEW_TITLE="chore(deps): $PR_TITLE"
            gh pr edit ${{ github.event.pull_request.number }} --title "$NEW_TITLE"
            echo "Updated title to: $NEW_TITLE"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
