name: Quality Checks

on:
  pull_request:
  push:
    branches:
      - '!main'

env:
  NODE_OPTIONS: --max_old_space_size=20480

jobs:
    quality:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up node.js 22
          uses: actions/setup-node@v3
          with:
            node-version: 22.x
        - name: Install dependencies
          run: npm ci
        - name: Run lint
          run: npm run lint:check
        - name: Run unit tests
          run: npm run test
